[build]
command = "npm run build"
publish = "dist"

[build.environment]
NODE_VERSION = "22.22.0"
NPM_VERSION = "10.9.4"
NPM_FLAGS = "--include=dev"
NPM_CONFIG_PRODUCTION = "false"
NODE_ENV = "development"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
